### ISSUE TITLE
Feat: Java/Kotlin Support

### ISSUE THREAD

**Issue by Cliftonz** [aserto-dev/topaz#16]
I believe that java would be a great expansion for this product as many enterprises uses java/kotlin for there backend systems.

**Comment by gertd** [comment]
Totally! It is on the top of the list of SDKs to add. We will start with publishing the gRPC language bindings for Java and build out an SDK from there. 

We can use some help in ensuring that the result is an idiomatic Java/Kotlin solution, as that is where we are lacking expertise right now.

**Comment by Cliftonz** [comment]
Awesome, thanks for the quick response!

**Comment by dgreene1** [comment]
I see that Aserto also doesn't have a Java SDK (current list link). When will these be available? Can we see dates on a roadmap? My company heavily uses Java and this is a barrier to entry.

Btw, what is the difference between Topaz and Aserto? Is one just the open source version and the other is the paid version that has a UI Console?

**Comment by ogazitt** [comment]
> I see that Aserto also doesn't have a Java SDK (current list link). When will these be available? Can we see dates on a roadmap? My company heavily uses Java and this is a barrier to entry.

@BogdanIrimie should be able to provide an update today.
 
> Btw, what is the difference between Topaz and Aserto? Is one just the open source version and the other is the paid version that has a UI Console?

Topaz is the open source authorization engine that Aserto is built on. Aserto provides a control plane and a management experience over Topaz authorizers.

**Comment by BogdanIrimie** [comment]
@dgreene1 @Cliftonz We are working on packaging the grpc java bindings and their dependencies in a maven artifact to make them easier to use. This will be available in the following days, I will keep you posted.

**Comment by gertd** [comment]
Today we release the first incarnation of our Java support, via our gRPC bindings for the authorizer and directory services. Please see https://github.com/aserto-dev/java-authorizer and https://github.com/aserto-dev/java-directory

**Comment by BogdanIrimie** [comment]
I am happy to announce the release of the [java sdk](https://github.com/aserto-dev/aserto-java). The artefact is available on maven central and getting started is as simple as adding the [dependency](https://central.sonatype.com/artifact/com.aserto/aserto-java/1.0.0) to your project.
