### ISSUE TITLE
2023/11/20 06:38:40 failed to create new config: unsupported config version

### ISSUE THREAD

**Issue by gavaskarentrans** [aserto-dev/topaz#191]
This error is showing in the latest version wheareas 0.25.16 working fine

**Comment by carabasdaniel** [comment]
Hello @gavaskarentrans, 

Between v0.25.16 and v0.30.x there has been a breaking change in the topaz configuration structure. The latest supported configuration file version is version 2. 

If you have a manually defined configuration file please see the detailed configuration changes here: https://github.com/aserto-dev/topaz/blob/main/docs/config.md

If you used **topaz CLI** to configure your topaz instance make sure you run the configuration command to update your config file and please make sure you have the latest topaz container image.

**Comment by gavaskarentrans** [comment]
thank you
