### ISSUE TITLE
Topaz Install fails due to permissions

### ISSUE THREAD

**Issue by Nassiel** [aserto-dev/topaz#23]
Hi,

After trying to install your product, I always get the same error. Because your packages (ghrc.io) are not open to download for not repo members. 

```
>>> installing topaz...
Error response from daemon: Head "https://ghcr.io/v2/aserto-dev/topaz/manifests/latest": denied: denied
topaz: error: running "docker pull ghcr.io/aserto-dev/topaz:latest" failed with exit code 1
```

I tried to log in with docker to ghrc.io, and despite its succeed, it still doesn't work.

Best!

**Comment by gertd** [comment]
Hi Nassiel, sorry for the trouble. Could you please provide details about the platform and version you are running on? Are you executing this locally or via a remote session (ssh), etc.?

**Comment by Nassiel** [comment]
Hi, I'm executing it locally on a Mac. The steps are:

- I install topaz though Brew
- In the terminal, I execute the command `topaz install`
- I get the error above

**Comment by gertd** [comment]
The container image is public, accessible at https://github.com/aserto-dev/topaz/pkgs/container/topaz

You could try pulling down the image using docker directly:

```docker pull ghcr.io/aserto-dev/topaz:latest```

**Comment by Nassiel** [comment]
Hi, 

I tried your docker pull. Here is the answer:
```
Error response from daemon: Head "https://ghcr.io/v2/aserto-dev/topaz/manifests/latest": denied: denied
```

If I try to access it with the curl, here is the detailed response:
```
*   Trying 140.82.121.33:443...
* Connected to ghcr.io (140.82.121.33) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /usr/local/anaconda3/ssl/cacert.pem
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=*.ghcr.io
*  start date: Jul 19 00:00:00 2022 GMT
*  expire date: Jul 19 23:59:59 2023 GMT
*  subjectAltName: host "ghcr.io" matched cert's "ghcr.io"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7faae680ce00)
> GET /v2/aserto-dev/topaz/manifests/latest HTTP/2
> Host: ghcr.io
> user-agent: curl/7.78.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 401 
< content-type: application/json
< www-authenticate: Bearer realm="https://ghcr.io/token",service="ghcr.io",scope="repository:aserto-dev/topaz:pull"
< date: Thu, 10 Nov 2022 08:55:04 GMT
< content-length: 73
< x-github-request-id: C6AB:13BC5:15FB022:16CD403:636CBC68
< 
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required"}]}
* Connection #0 to host ghcr.io left intact
```

If auth header is required, it means that it's not public. I consider it very weird that only 3 people downloaded the latest version, most of which are 1 or 0, 11 the most. Your software is that unknown?

**Comment by ogazitt** [comment]
The `ghcr.io/aserto-dev/topaz:latest` image is public. It's weird that the docker pull doesn't work for you.

For what it's worth, GitHub doesn't appear to support curl'ing a manifest without an auth header, even for public images. (Try it with any public image).

As far as number of pulls, Topaz just launched, so it's still early days!

**Comment by Nassiel** [comment]
Ok, now I feel stupid, my personal access token was revoked by my enterprise. Now I could access it without any issue after re-doing the docker login. 

As for the number of pulls, pretty impressive that you have such amount of releases already!

Lastly, I apologise for the inconvenience and thanks for the great support :)

**Comment by ogazitt** [comment]
Thanks Nassiel, glad you were able to figure it out! Please let us know if you have any other issues :)
