### ISSUE TITLE
Issues with "Getting started" tutorial

### ISSUE THREAD

**Issue by amOgury** [aserto-dev/topaz#242]
Hello,

I'm discovering the Topaz and have some issues with the "Getting started" tutorial.

1. On the [Create configuration](https://www.topaz.sh/docs/getting-started#create-a-configuration) step, **`-s` parameter is not recognised during the Todo policy import**: 

```
% topaz configure -d -s -r ghcr.io/aserto-policies/policy-todo-rebac:latest -n policy-todo
...
topaz: error: unknown flag -s, did you mean one of "-h", "-N", "-n", "-l", "-r", "-p", "-d", "-f"?
```
I'm just re-running the same command, but without `-s`, is it ok?

2. During the [Test your server with the Todo web application](https://www.topaz.sh/docs/getting-started/samples/test-application), **"admin" `rick@the-citadel.com` is not able to create TODOs**:

On the `todo-node-js-v2` backend:
```
2024-01-19T09:00:57.018Z ERROR: Forbidden by policy todoApp.POST.todos
```
When querying Topaz directly:
```
% curl -k -X POST 'https://localhost:8383/api/v2/authz/is' \
-H 'Content-Type: application/json' \
-d '{
     "identity_context": {
          "type": "IDENTITY_TYPE_SUB",
          "identity": "rick@the-citadel.com"
     },
     "policy_context": {
          "path": "todoApp.POST.todos",
          "decisions": ["allowed"]
     }
}'
{
  "decisions":  [
    {
      "decision":  "allowed",
      "is":  false
    }
  ]
}% 
```
The expected behaviour is to receive `"is":  true` as "admin" is allowed in "todoApp.POST.todos" module.

I'm on macOS Sonoma 14.2.1, topaz was installed via `brew` and have version `topaz 0.30.28 g314bbcd darwin-arm64 [2024-01-15T21:21:08Z]`

Help is appreciated,
Anton

**Comment by ogazitt** [comment]
Hi Anton, I haven't been able to repro what you're seeing.

```
curl -k -X POST 'https://localhost:8383/api/v2/authz/is' \
-H 'Content-Type: application/json' \
-d '{
     "identity_context": {
          "type": "IDENTITY_TYPE_SUB",
          "identity": "rick@the-citadel.com"
     },
     "policy_context": {
          "path": "todoApp.POST.todos",
          "decisions": ["allowed"]
     }
}'
{
  "decisions":  [
    {
      "decision":  "allowed",
      "is":  true
    }
  ]
}%
```

Were you able to import the sample data [here](https://www.topaz.sh/docs/getting-started#import-sample-data)?

You can also issue a `topaz console` to see whether you have data, and to evaluate queries within the UI.

**Comment by ogazitt** [comment]
Also, thanks for reporting the issue on the docs still referencing the `-s` flag. That's been fixed: https://github.com/aserto-dev/topaz-website/pull/79

**Comment by amOgury** [comment]
Hello Omri,

Thanks for having a look into the issues!

I can confirm that the sample data was properly imported, but nevertheless the issue with `ERROR: Forbidden by policy todoApp.POST.todos` still persist.

I asked my co-worker to follow tutorial steps on his machine and he have exactly same issue.

Also, i can confirm that `todoApp.GET.todos` policy is evaluated correctly, but not `todoApp.POST.todos` one:

```
% curl -k -X POST 'https://localhost:8383/api/v2/authz/is' \
-H 'Content-Type: application/json' \
-d '{
     "identity_context": {
          "type": "IDENTITY_TYPE_SUB",
          "identity": "rick@the-citadel.com"
     },
     "policy_context": {
          "path": "todoApp.GET.todos", 
          "decisions": ["allowed"]
     }
}'

{
  "decisions":  [
    {
      "decision":  "allowed",
      "is":  true
    }
  ]
}% 
```
```
% curl -k -X POST 'https://localhost:8383/api/v2/authz/is' \
-H 'Content-Type: application/json' \
-d '{
     "identity_context": {
          "type": "IDENTITY_TYPE_SUB",
          "identity": "rick@the-citadel.com"
     },
     "policy_context": {
          "path": "todoApp.POST.todos",
          "decisions": ["allowed"]
     }
}'

{
  "decisions":  [
    {
      "decision":  "allowed",
      "is":  false
    }
  ]
}% 
```

Please let me know if you have other ideas how to investigate that.

**Comment by ogazitt** [comment]
Thanks Anton, I've confirmed that on a clean install, the directions you've followed indeed have missed a step. We recently removed the "directory seeding" option from the "configure" command (`-s`) in favor of explicitly setting a manifest, which defines a set of core types (e.g. `user`, `group`, etc).

We just shipped a new feature, templates, which handles all the configuration in a single step: set a manifest, set a policy, and import the template data. We just haven't brought the docs up to date yet 😅 

The easiest way to get a working configuration for the todo app is `topaz templates install todo`.  This will ensure that you have the correct manifest, and the `curl` you mentioned should now work.

Please let us know if that didn't clear up the issue!
