### ISSUE TITLE
Scalability questions

### ISSUE THREAD

**Issue by amOgury** [aserto-dev/topaz#243]
Hello,

We are considering to deploy Topaz as a micorservice inside our organisation to handle user's authorisations for a new project.
I have some questions/doubts regarding the scalability of such approach:

1. As you're using [bbolt](https://github.com/etcd-io/bbolt) DB, which is an embedded Key-Value DB, does it means that it's is only possible to have 1 single instance of Topaz? (so, only vertical scaling is possible)
2. With a single instance, how to avoid it be a single point of failure?
3. If we deploy several instances of Topaz, is it possible to setup a sync data between them?
4. Do you have an mechanism for automatic backup/restore of DB?

Thanks in advance,
Anton

**Comment by ogazitt** [comment]
Hi Anton,

As you mentioned, Topaz includes an embedded DB that stores objects and relationships. Topaz consumes a gRPC contract for talking to a data store, and the embedded DB is one implementation of that contract. We have a postgres implementation as well (part of the Aserto commercial offering).

There are two strategies for keeping data in sync between Topaz instances:
1. Eventual consistency: data changes are made into each Topaz instance. You can either do this yourself (in code), or you can use the Aserto central directory and connect the Topaz instances to the Aserto control plane, which will distribute data changes to any Topaz instance that is connected to the control plane.
2. Stateless Topaz: Use a postgres-backed relational directory implementation, and configure the Topaz instances to talk to this directory.

Question 2: with either of these models, you can scale Topaz instances horizontally (no SPOF).

Question 3: the [Aserto control plane](https://docs.aserto.com/docs/overview/control-plane) was built to solve this problem.

Question 4: if you're running the [Aserto Directory](https://docs.aserto.com/docs/local-deployment/local-directory/overview) in your cloud, you can use your cloud provider's auto backup/restore (e.g. AWS RDS) for the Postgres instance.

**Comment by amOgury** [comment]
Hi Omri,

Thanks for your detailed answers!

Considering your commercial offer, I have few more questions:

1. Is it possible to start with Topaz on our side but later switch to the Aserto commercial offering? What are the potential blockers that we may face?
2. Do you have any official migration guide from Topaz to Aserto?
3. Do you provide any support in doing this migration?

Many thanks

**Comment by ogazitt** [comment]
Thanks Anton!

1. Yes, you can start with "single-instance" Topaz, and when you're ready, you can connect that Topaz instance to the Aserto control plane. It's as easy as changing the Topaz config.yaml file.
2. The process is meant to be very simple. You create an Aserto tenant, install the `aserto` CLI, run `aserto developer configure`, which will create a topaz config file with the correct sections to connect the topaz instance to the Aserto control plane.
3. If you're a commercial customer, yes, we will definitely help you set this up!

**Comment by ogazitt** [comment]
@amOgury does this answer your questions?

**Comment by ogazitt** [comment]
@amOgury since we haven't heard back, I'm closing this issue - please feel free to re-open it if you need more information. Thanks!
