### ISSUE TITLE
How is topaz similar/different to OPAL?

### ISSUE THREAD

**Issue by keshavkaul** [aserto-dev/topaz#458]
OPAL (https://opal.ac) allows to orchestrate OPA policy and data dynamically and is deployed as a sidecar with the applications. Curious to understand how topaz is similar or different to OPAL.

**Comment by ogazitt** [comment]
Topaz is an authorizer (PDP) - it is a superset of OPA. Topaz uses OPA as a decision engine, but adds an embedded ReBAC (Zanzibar) database for storing and demand-loading objects and relations, and efficiently computing “check” and “search” calls. 

OPAL is not a PDP itself. It is a control plane that keeps a PDP (typically OPA) up-to-date. 

Aserto has a control plane (similar to OPAL) which keeps policies and data up-to-date.

**Comment by ogazitt** [comment]
I hope the explanation made sense... closing this issue.
