### ISSUE TITLE
Typos in directory writer API docs

### ISSUE THREAD

**Issue by 0x00A5** [aserto-dev/topaz#84]
In the [directory writer API doc page](https://www.topaz.sh/docs/directory/writer), the headline is,

> The Directory Reader APIs are in the `aserto.directory.reader.v2.Reader` service.

which seems wrong.

**Comment by ronenh** [comment]
Good catch! Thanks for reporting it. 
This should read `aserto.directory.writer.v2.Writer` of course.
We'll fix it shortly.
